package io.udash.bootstrap

import io.udash.css.CssStyleName

object BootstrapTags {
  import scalatags.JsDom.all._

  val dataBackdrop = attr("data-backdrop")
  val dataBind = attr("data-bind")
  val dataDismiss = attr("data-dismiss")
  val dataKeyboard = attr("data-keyboard")
  val dataLabel = attr("data-label")
  val dataParent = attr("data-parent")
  val dataRide = attr("data-ride")
  val dataShow = attr("data-show")
  val dataSlide = attr("data-slide")
  val dataSlideTo = attr("data-slide-to")
  val dataTarget = attr("data-target")
  val dataToggle = attr("data-toggle")

}

object BootstrapStyles {
  def active = CssStyleName("active")
  def container = CssStyleName("container")
  def containerFluid = CssStyleName("container-fluid")
  def row = CssStyleName("row")
  def pullLeft = CssStyleName("pull-left")
  def pullRight = CssStyleName("pull-right")
  def centerBlock = CssStyleName("center-block")
  def affix = CssStyleName("affix")
  def arrow = CssStyleName("arrow")
  def bottom = CssStyleName("bottom")
  def close = CssStyleName("close")
  def col = CssStyleName("col")
  def collapsed = CssStyleName("collapsed")
  def body = container
  def divider = CssStyleName("divider")
  def disabled = CssStyleName("disabled")
  def fade = CssStyleName("fade")
  def hide = CssStyleName("hide")
  def iconBar = CssStyleName("icon-bar")
  def iconNext = CssStyleName("icon-next")
  def in = CssStyleName("in")
  def item = CssStyleName("item")
  def jumbotron = CssStyleName("jumbotron")
  def left = CssStyleName("left")
  def next = CssStyleName("next")
  def pillPane = CssStyleName("pill-pane")
  def preScrollable = CssStyleName("pre-scrollable")
  def prettyprint = CssStyleName("prettyprint")
  def previous = CssStyleName("previous")
  def prev = CssStyleName("prev")
  def right = CssStyleName("right")
  def show = CssStyleName("show")
  def top = CssStyleName("top")

  object Collapse {
    def collapse = CssStyleName("collapse")
    def collapsing = CssStyleName("collapsing")
    def collapseIn = in
  }

  object Grid {
    def colXl1 = CssStyleName("col-xl-1")
    def colXl10 = CssStyleName("col-xl-10")
    def colXl11 = CssStyleName("col-xl-11")
    def colXl12 = CssStyleName("col-xl-12")
    def colXl2 = CssStyleName("col-xl-2")
    def colXl3 = CssStyleName("col-xl-3")
    def colXl4 = CssStyleName("col-xl-4")
    def colXl5 = CssStyleName("col-xl-5")
    def colXl6 = CssStyleName("col-xl-6")
    def colXl7 = CssStyleName("col-xl-7")
    def colXl8 = CssStyleName("col-xl-8")
    def colXl9 = CssStyleName("col-xl-9")
    def offsetXl0 = CssStyleName("offset-xl-0")
    def offsetXl1 = CssStyleName("offset-xl-1")
    def offsetXl10 = CssStyleName("offset-xl-10")
    def offsetXl11 = CssStyleName("offset-xl-11")
    def offsetXl2 = CssStyleName("offset-xl-2")
    def offsetXl3 = CssStyleName("offset-xl-3")
    def offsetXl4 = CssStyleName("offset-xl-4")
    def offsetXl5 = CssStyleName("offset-xl-5")
    def offsetXl6 = CssStyleName("offset-xl-6")
    def offsetXl7 = CssStyleName("offset-xl-7")
    def offsetXl8 = CssStyleName("offset-xl-8")
    def offsetXl9 = CssStyleName("offset-xl-9")
    def colLg1 = CssStyleName("col-lg-1")
    def colLg10 = CssStyleName("col-lg-10")
    def colLg11 = CssStyleName("col-lg-11")
    def colLg12 = CssStyleName("col-lg-12")
    def colLg2 = CssStyleName("col-lg-2")
    def colLg3 = CssStyleName("col-lg-3")
    def colLg4 = CssStyleName("col-lg-4")
    def colLg5 = CssStyleName("col-lg-5")
    def colLg6 = CssStyleName("col-lg-6")
    def colLg7 = CssStyleName("col-lg-7")
    def colLg8 = CssStyleName("col-lg-8")
    def colLg9 = CssStyleName("col-lg-9")
    def offsetLg0 = CssStyleName("offset-lg-0")
    def offsetLg1 = CssStyleName("offset-lg-1")
    def offsetLg10 = CssStyleName("offset-lg-10")
    def offsetLg11 = CssStyleName("offset-lg-11")
    def offsetLg2 = CssStyleName("offset-lg-2")
    def offsetLg3 = CssStyleName("offset-lg-3")
    def offsetLg4 = CssStyleName("offset-lg-4")
    def offsetLg5 = CssStyleName("offset-lg-5")
    def offsetLg6 = CssStyleName("offset-lg-6")
    def offsetLg7 = CssStyleName("offset-lg-7")
    def offsetLg8 = CssStyleName("offset-lg-8")
    def offsetLg9 = CssStyleName("offset-lg-9")
    def colMd1 = CssStyleName("col-md-1")
    def colMd10 = CssStyleName("col-md-10")
    def colMd11 = CssStyleName("col-md-11")
    def colMd12 = CssStyleName("col-md-12")
    def colMd2 = CssStyleName("col-md-2")
    def colMd3 = CssStyleName("col-md-3")
    def colMd4 = CssStyleName("col-md-4")
    def colMd5 = CssStyleName("col-md-5")
    def colMd6 = CssStyleName("col-md-6")
    def colMd7 = CssStyleName("col-md-7")
    def colMd8 = CssStyleName("col-md-8")
    def colMd9 = CssStyleName("col-md-9")
    def offsetMd0 = CssStyleName("offset-md-0")
    def offsetMd1 = CssStyleName("offset-md-1")
    def offsetMd10 = CssStyleName("offset-md-10")
    def offsetMd11 = CssStyleName("offset-md-11")
    def offsetMd2 = CssStyleName("offset-md-2")
    def offsetMd3 = CssStyleName("offset-md-3")
    def offsetMd4 = CssStyleName("offset-md-4")
    def offsetMd5 = CssStyleName("offset-md-5")
    def offsetMd6 = CssStyleName("offset-md-6")
    def offsetMd7 = CssStyleName("offset-md-7")
    def offsetMd8 = CssStyleName("offset-md-8")
    def offsetMd9 = CssStyleName("offset-md-9")
    def colSm1 = CssStyleName("col-sm-1")
    def colSm10 = CssStyleName("col-sm-10")
    def colSm11 = CssStyleName("col-sm-11")
    def colSm12 = CssStyleName("col-sm-12")
    def colSm2 = CssStyleName("col-sm-2")
    def colSm3 = CssStyleName("col-sm-3")
    def colSm4 = CssStyleName("col-sm-4")
    def colSm5 = CssStyleName("col-sm-5")
    def colSm6 = CssStyleName("col-sm-6")
    def colSm7 = CssStyleName("col-sm-7")
    def colSm8 = CssStyleName("col-sm-8")
    def colSm9 = CssStyleName("col-sm-9")
    def offsetSm1 = CssStyleName("offset-sm-1")
    def offsetSm10 = CssStyleName("offset-sm-10")
    def offsetSm11 = CssStyleName("offset-sm-11")
    def offsetSm2 = CssStyleName("offset-sm-2")
    def offsetSm3 = CssStyleName("offset-sm-3")
    def offsetSm4 = CssStyleName("offset-sm-4")
    def offsetSm5 = CssStyleName("offset-sm-5")
    def offsetSm6 = CssStyleName("offset-sm-6")
    def offsetSm7 = CssStyleName("offset-sm-7")
    def offsetSm8 = CssStyleName("offset-sm-8")
    def offsetSm9 = CssStyleName("offset-sm-9")
    def col1 = CssStyleName("col-1")
    def col10 = CssStyleName("col-10")
    def col11 = CssStyleName("col-11")
    def col12 = CssStyleName("col-12")
    def col2 = CssStyleName("col-2")
    def col3 = CssStyleName("col-3")
    def col4 = CssStyleName("col-4")
    def col5 = CssStyleName("col-5")
    def col6 = CssStyleName("col-6")
    def col7 = CssStyleName("col-7")
    def col8 = CssStyleName("col-8")
    def col9 = CssStyleName("col-9")
    def order1 = CssStyleName("order-1")
    def order10 = CssStyleName("order-10")
    def order11 = CssStyleName("order-11")
    def order12 = CssStyleName("order-12")
    def order2 = CssStyleName("order-2")
    def order3 = CssStyleName("order-3")
    def order4 = CssStyleName("order-4")
    def order5 = CssStyleName("order-5")
    def order6 = CssStyleName("order-6")
    def order7 = CssStyleName("order-7")
    def order8 = CssStyleName("order-8")
    def order9 = CssStyleName("order-9")
  }

  object Background {
    def bgPrimary = CssStyleName("bg-primary")
    def bgSuccess = CssStyleName("bg-success")
    def bgInfo = CssStyleName("bg-info")
    def bgWarning = CssStyleName("bg-warning")
    def bgDanger = CssStyleName("bg-danger")
  }

  object Button {
    def btn = CssStyleName("btn")
    def btnBlock = CssStyleName("btn-block")
    def btnDanger = CssStyleName("btn-danger")
    def btnDefault = CssStyleName("btn-default")
    def btnGroup = CssStyleName("btn-group")
    def btnGroupJustified = CssStyleName("btn-group-justified")
    def btnGroupVertical = CssStyleName("btn-group-vertical")
    def btnInfo = CssStyleName("btn-info")
    def btnLg = CssStyleName("btn-lg")
    def btnLink = CssStyleName("btn-link")
    def btnPrimary = CssStyleName("btn-primary")
    def btnSuccess = CssStyleName("btn-success")
    def btnToolbar = CssStyleName("btn-toolbar")
    def btnWarning = CssStyleName("btn-warning")
    def btnXs = CssStyleName("btn-xs")
    def btnSm = CssStyleName("btn-sm")
  }

  object Well {
    def well = CssStyleName("well")
    def wellLg = CssStyleName("well-lg")
    def wellSm = CssStyleName("well-sm")
  }

  object Carousel {
    def carousel = CssStyleName("carousel")
    def carouselCaption = CssStyleName("carousel-caption")
    def carouselControl = CssStyleName("carousel-control")
    def carouselIndicators = CssStyleName("carousel-indicators")
    def carouselInner = CssStyleName("carousel-inner")
    def slide = CssStyleName("slide")
  }

  object Alert {
    def alert = CssStyleName("alert")
    def alertDanger = CssStyleName("alert-danger")
    def alertDismissible = CssStyleName("alert-dismissible")
    def alertInfo = CssStyleName("alert-info")
    def alertLink = CssStyleName("alert-link")
    def alertSuccess = CssStyleName("alert-success")
    def alertWarning = CssStyleName("alert-warning")
  }

  object Dropdown {
    def dropdown = CssStyleName("dropdown")
    def dropdownBackdrop = CssStyleName("dropdown-backdrop")
    def dropdownHeader = CssStyleName("dropdown-header")
    def dropdownMenu = CssStyleName("dropdown-menu")
    def dropdownToggle = CssStyleName("dropdown-toggle")
    def dropup = CssStyleName("dropup")
    def caret = CssStyleName("caret")
  }

  object Visibility {
    def clearfix = CssStyleName("clearfix")
    def hidden = CssStyleName("hidden")
    def hiddenLg = CssStyleName("hidden-lg")
    def hiddenMd = CssStyleName("hidden-md")
    def hiddenPrint = CssStyleName("hidden-print")
    def hiddenSm = CssStyleName("hidden-sm")
    def hiddenXs = CssStyleName("hidden-xs")
    def visibleLg = CssStyleName("visible-lg")
    def visibleMd = CssStyleName("visible-md")
    def visiblePrint = CssStyleName("visible-print")
    def visibleSm = CssStyleName("visible-sm")
    def visibleXs = CssStyleName("visible-xs")
    def invisible = CssStyleName("invisible")
    def srOnly = CssStyleName("sr-only")
    def srOnlyFocusable = CssStyleName("sr-only-focusable")
  }

  object Typography {
    def h1 = CssStyleName("h1")
    def h2 = CssStyleName("h2")
    def h3 = CssStyleName("h3")
    def h4 = CssStyleName("h4")
    def h5 = CssStyleName("h5")
    def h6 = CssStyleName("h6")
    def lead = CssStyleName("lead")
    def textCenter = CssStyleName("text-center")
    def textDanger = CssStyleName("text-danger")
    def textHide = CssStyleName("text-hide")
    def textInfo = CssStyleName("text-info")
    def textLeft = CssStyleName("text-left")
    def textMuted = CssStyleName("text-muted")
    def textPrimary = CssStyleName("text-primary")
    def textRight = CssStyleName("text-right")
    def textSuccess = CssStyleName("text-success")
    def textWarning = CssStyleName("text-warning")
    def textNoWrap = CssStyleName("text-nowrap")
    def textLowercase = CssStyleName("text-lowercase")
    def textUppercase = CssStyleName("text-uppercase")
    def textCapitalize = CssStyleName("text-capitalize")
    def initialism = CssStyleName("initialism")
    def blockquote = CssStyleName("blockquote")
  }

  object List {
    def listGroup = CssStyleName("list-group")
    def listGroupItem = CssStyleName("list-group-item")
    def listGroupItemHeading = CssStyleName("list-group-item-heading")
    def listGroupItemText = CssStyleName("list-group-item-text")
    def listInline = CssStyleName("list-inline")
    def listUnstyled = CssStyleName("list-unstyled")
    def listItemSuccess = CssStyleName("list-group-item-success")
    def listItemInfo = CssStyleName("list-group-item-info")
    def listItemWarning = CssStyleName("list-group-item-warning")
    def listItemDanger = CssStyleName("list-group-item-danger")
  }

  object Table {
    def table = CssStyleName("table")
    def tableBordered = CssStyleName("table-bordered")
    def tableResponsive = CssStyleName("table-responsive")
    def tableStriped = CssStyleName("table-striped")
    def tableHover = CssStyleName("table-hover")
    def tableSm = CssStyleName("table-sm")
    def tableInverse = CssStyleName("table-inverse")
    def success = CssStyleName("success")
    def tableInfo = CssStyleName("info")
    def tableWarning = CssStyleName("warning")
    def tableDanger = CssStyleName("danger")
    def tableActive = CssStyleName("active")
    def tableSuccess = CssStyleName("success")
    def theadDefault = CssStyleName("thead-default")
    def theadInverse = CssStyleName("thead-inverse")
  }

  object Form {
    def formCheck = CssStyleName("form-check")
    def formCheckInline = CssStyleName("form-check-inline")
    def formCheckInput = CssStyleName("form-check-input")
    def formCheckLabel = CssStyleName("form-check-label")
    def formControl = CssStyleName("form-control")
    def formControlPlaintext = CssStyleName("form-control-plaintext")
    def formGroup = CssStyleName("form-group")
    def formInline = CssStyleName("form-inline")
    def inputGroup = CssStyleName("input-group")
    def inputGroupAppend = CssStyleName("input-group-append")
    def inputGroupPrepend = CssStyleName("input-group-prepend")
    def inputGroupLg = CssStyleName("input-group-lg")
    def inputGroupSm = CssStyleName("input-group-sm")
    def inputGroupText = CssStyleName("input-group-text")
    def formControlLg = CssStyleName("form-control-lg")
    def formControlSm = CssStyleName("form-control-sm")
    def hasFeedback = CssStyleName("has-feedback")
    def formText = CssStyleName("form-text")
    def colFormLabel = CssStyleName("col-form-label")
  }

  object Image {
    def roundedCircle = CssStyleName("rounded-circle")
    def imgFluid = CssStyleName("img-fluid")
    def ounded = CssStyleName("rounded")
    def imgThumbnail = CssStyleName("img-thumbnail")
    def caption = CssStyleName("caption")
    def thumbnail = CssStyleName("thumbnail")

    @deprecated("Use `UdashIcons.FontAwesome` styles instead.", "0.6.0")
    def _fa = CssStyleName("fa")
    @deprecated("Use `UdashIcons.Glyphicon` styles instead.", "0.6.0")
    def _glyphicon = CssStyleName("glyphicon")

    @deprecated("Use `UdashIcons.FontAwesome` instead.", "0.6.0")
    def fa(name: String) = Seq(_fa, CssStyleName(s"fa-$name"))
    @deprecated("Use `UdashIcons.FontAwesome` instead.", "0.6.0")
    def glyphicon(name: String) = Seq(_glyphicon, CssStyleName(s"glyphicon-$name"))
  }

  object Navigation {
    def nav = CssStyleName("nav")
    def navbar = CssStyleName("navbar")
    def navbarBrand = CssStyleName("navbar-brand")
    def navbarBtn = CssStyleName("navbar-btn")
    def navbarCollapse = CssStyleName("navbar-collapse")
    def navbarDefault = CssStyleName("navbar-default")
    def navbarFixedBottom = CssStyleName("navbar-fixed-bottom")
    def navbarFixedTop = CssStyleName("navbar-fixed-top")
    def navbarForm = CssStyleName("navbar-form")
    def navbarHeader = CssStyleName("navbar-header")
    def navbarInverse = CssStyleName("navbar-inverse")
    def navbarLeft = CssStyleName("navbar-left")
    def navbarLink = CssStyleName("navbar-link")
    def navbarNav = CssStyleName("navbar-nav")
    def navbarRight = CssStyleName("navbar-right")
    def navbarStaticTop = CssStyleName("navbar-static-top")
    def navbarText = CssStyleName("navbar-text")
    def navbarToggle = CssStyleName("navbar-toggle")
    def navDivider = CssStyleName("nav-divider")
    def navJustified = CssStyleName("nav-justified")
    def navStacked = CssStyleName("nav-stacked")
    def navPills = CssStyleName("nav-pills")
    def navTabs = CssStyleName("nav-tabs")
    def navTabsJustified = CssStyleName("nav-tabs-justified")
    def breadcrumb = CssStyleName("breadcrumb")
  }

  object Label {
    def badge = CssStyleName("badge")
    def label = CssStyleName("label")
    def labelDanger = CssStyleName("label-danger")
    def labelDefault = CssStyleName("label-default")
    def labelInfo = CssStyleName("label-info")
    def labelPrimary = CssStyleName("label-primary")
    def labelSuccess = CssStyleName("label-success")
    def labelWarning = CssStyleName("label-warning")
  }

  object Media {
    def media = CssStyleName("media")
    def mediaBody = CssStyleName("media-body")
    def mediaHeading = CssStyleName("media-heading")
    def mediaList = CssStyleName("media-list")
    def mediaObject = CssStyleName("media-object")
    def mediaLeft = CssStyleName("media-left")
    def mediaMiddle = CssStyleName("media-middle")
    def mediaRight = CssStyleName("media-right")
  }

  object Modal {
    def modal = CssStyleName("modal")
    def modalBackdrop = CssStyleName("modal-backdrop")
    def modalBody = CssStyleName("modal-body")
    def modalContent = CssStyleName("modal-content")
    def modalDialog = CssStyleName("modal-dialog")
    def modalFooter = CssStyleName("modal-footer")
    def modalHeader = CssStyleName("modal-header")
    def modalLarge = CssStyleName("modal-lg")
    def modalOpen = CssStyleName("modal-open")
    def modalSmall = CssStyleName("modal-sm")
    def modalTitle = CssStyleName("modal-title")
  }

  object Pagination {
    def pagination = CssStyleName("pagination")
    def paginationLg = CssStyleName("pagination-lg")
    def paginationSm = CssStyleName("pagination-sm")
    def pager = CssStyleName("pager")
  }

  object Panel {
    def panel = CssStyleName("panel")
    def panelBody = CssStyleName("panel-body")
    def panelCollapse = CssStyleName("panel-collapse")
    def panelDanger = CssStyleName("panel-danger")
    def panelDefault = CssStyleName("panel-default")
    def panelFooter = CssStyleName("panel-footer")
    def panelGroup = CssStyleName("panel-group")
    def panelHeading = CssStyleName("panel-heading")
    def panelInfo = CssStyleName("panel-info")
    def panelPrimary = CssStyleName("panel-primary")
    def panelSuccess = CssStyleName("panel-success")
    def panelTitle = CssStyleName("panel-title")
    def panelWarning = CssStyleName("panel-warning")
  }

  object Popover {
    def popover = CssStyleName("popover")
    def popoverContent = CssStyleName("popover-content")
    def popoverTitle = CssStyleName("popover-title")
  }

  object ProgressBar {
    def progress = CssStyleName("progress")
    def progressBar = CssStyleName("progress-bar")
    def progressBarDanger = CssStyleName("progress-bar-danger")
    def progressBarInfo = CssStyleName("progress-bar-info")
    def progressBarSuccess = CssStyleName("progress-bar-success")
    def progressBarWarning = CssStyleName("progress-bar-warning")
    def progressBarStriped = CssStyleName("progress-bar-striped")
  }

  object Tooltip {
    def tooltip = CssStyleName("tooltip")
    def tooltipArrow = CssStyleName("tooltip-arrow")
    def tooltipInner = CssStyleName("tooltip-inner")
  }

  object EmbedResponsive {
    def embed = CssStyleName("embed-responsive")
    def item = CssStyleName("embed-responsive-item")
    def embed16by9 = CssStyleName("embed-responsive-16by9")
    def embed4by3 = CssStyleName("embed-responsive-4by3")
  }
}