package io.udash.bootstrap

import io.udash.css.CssStyleName

import scala.language.postfixOps

object BootstrapTags {
  import scalatags.JsDom.all._

  val dataBackdrop = attr("data-backdrop")
  val dataBind = attr("data-bind")
  val dataDismiss = attr("data-dismiss")
  val dataKeyboard = attr("data-keyboard")
  val dataLabel = attr("data-label")
  val dataParent = attr("data-parent")
  val dataRide = attr("data-ride")
  val dataShow = attr("data-show")
  val dataSlide = attr("data-slide")
  val dataSlideTo = attr("data-slide-to")
  val dataTarget = attr("data-target")
  val dataToggle = attr("data-toggle")

}

object BootstrapStyles {
  val active = CssStyleName("active")
  val container = CssStyleName("container")
  val containerFluid = CssStyleName("container-fluid")
  val row = CssStyleName("row")
  val pullLeft = CssStyleName("pull-left")
  val pullRight = CssStyleName("pull-right")
  val centerBlock = CssStyleName("center-block")
  val affix = CssStyleName("affix")
  val arrow = CssStyleName("arrow")
  val bottom = CssStyleName("bottom")
  val close = CssStyleName("close")
  val col = CssStyleName("col")
  val collapsed = CssStyleName("collapsed")
  val body = container
  val divider = CssStyleName("divider")
  val disabled = CssStyleName("disabled")
  val fade = CssStyleName("fade")
  val hide = CssStyleName("hide")
  val iconBar = CssStyleName("icon-bar")
  val iconNext = CssStyleName("icon-next")
  val in = CssStyleName("in")
  val item = CssStyleName("item")
  val jumbotron = CssStyleName("jumbotron")
  val left = CssStyleName("left")
  val next = CssStyleName("next")
  val pillPane = CssStyleName("pill-pane")
  val preScrollable = CssStyleName("pre-scrollable")
  val prettyprint = CssStyleName("prettyprint")
  val previous = CssStyleName("previous")
  val prev = CssStyleName("prev")
  val right = CssStyleName("right")
  val show = CssStyleName("show")
  val top = CssStyleName("top")

  object Collapse {
    val collapse = CssStyleName("collapse")
    val collapsing = CssStyleName("collapsing")
    val collapseIn = in
  }

  object Grid {
    val colLg1 = CssStyleName("col-lg-1")
    val colLg10 = CssStyleName("col-lg-10")
    val colLg11 = CssStyleName("col-lg-11")
    val colLg12 = CssStyleName("col-lg-12")
    val colLg2 = CssStyleName("col-lg-2")
    val colLg3 = CssStyleName("col-lg-3")
    val colLg4 = CssStyleName("col-lg-4")
    val colLg5 = CssStyleName("col-lg-5")
    val colLg6 = CssStyleName("col-lg-6")
    val colLg7 = CssStyleName("col-lg-7")
    val colLg8 = CssStyleName("col-lg-8")
    val colLg9 = CssStyleName("col-lg-9")
    val colLgOffset0 = CssStyleName("col-lg-offset-0")
    val colLgOffset1 = CssStyleName("col-lg-offset-1")
    val colLgOffset10 = CssStyleName("col-lg-offset-10")
    val colLgOffset11 = CssStyleName("col-lg-offset-11")
    val colLgOffset2 = CssStyleName("col-lg-offset-2")
    val colLgOffset3 = CssStyleName("col-lg-offset-3")
    val colLgOffset4 = CssStyleName("col-lg-offset-4")
    val colLgOffset5 = CssStyleName("col-lg-offset-5")
    val colLgOffset6 = CssStyleName("col-lg-offset-6")
    val colLgOffset7 = CssStyleName("col-lg-offset-7")
    val colLgOffset8 = CssStyleName("col-lg-offset-8")
    val colLgOffset9 = CssStyleName("col-lg-offset-9")
    val colLgPull0 = CssStyleName("col-lg-pull-0")
    val colLgPull1 = CssStyleName("col-lg-pull-1")
    val colLgPull10 = CssStyleName("col-lg-pull-10")
    val colLgPull11 = CssStyleName("col-lg-pull-11")
    val colLgPull2 = CssStyleName("col-lg-pull-2")
    val colLgPull3 = CssStyleName("col-lg-pull-3")
    val colLgPull4 = CssStyleName("col-lg-pull-4")
    val colLgPull5 = CssStyleName("col-lg-pull-5")
    val colLgPull6 = CssStyleName("col-lg-pull-6")
    val colLgPull7 = CssStyleName("col-lg-pull-7")
    val colLgPull8 = CssStyleName("col-lg-pull-8")
    val colLgPull9 = CssStyleName("col-lg-pull-9")
    val colLgPush0 = CssStyleName("col-lg-push-0")
    val colLgPush1 = CssStyleName("col-lg-push-1")
    val colLgPush10 = CssStyleName("col-lg-push-10")
    val colLgPush11 = CssStyleName("col-lg-push-11")
    val colLgPush2 = CssStyleName("col-lg-push-2")
    val colLgPush3 = CssStyleName("col-lg-push-3")
    val colLgPush4 = CssStyleName("col-lg-push-4")
    val colLgPush5 = CssStyleName("col-lg-push-5")
    val colLgPush6 = CssStyleName("col-lg-push-6")
    val colLgPush7 = CssStyleName("col-lg-push-7")
    val colLgPush8 = CssStyleName("col-lg-push-8")
    val colLgPush9 = CssStyleName("col-lg-push-9")
    val colMd1 = CssStyleName("col-md-1")
    val colMd10 = CssStyleName("col-md-10")
    val colMd11 = CssStyleName("col-md-11")
    val colMd12 = CssStyleName("col-md-12")
    val colMd2 = CssStyleName("col-md-2")
    val colMd3 = CssStyleName("col-md-3")
    val colMd4 = CssStyleName("col-md-4")
    val colMd5 = CssStyleName("col-md-5")
    val colMd6 = CssStyleName("col-md-6")
    val colMd7 = CssStyleName("col-md-7")
    val colMd8 = CssStyleName("col-md-8")
    val colMd9 = CssStyleName("col-md-9")
    val colMdOffset0 = CssStyleName("col-md-offset-0")
    val colMdOffset1 = CssStyleName("col-md-offset-1")
    val colMdOffset10 = CssStyleName("col-md-offset-10")
    val colMdOffset11 = CssStyleName("col-md-offset-11")
    val colMdOffset2 = CssStyleName("col-md-offset-2")
    val colMdOffset3 = CssStyleName("col-md-offset-3")
    val colMdOffset4 = CssStyleName("col-md-offset-4")
    val colMdOffset5 = CssStyleName("col-md-offset-5")
    val colMdOffset6 = CssStyleName("col-md-offset-6")
    val colMdOffset7 = CssStyleName("col-md-offset-7")
    val colMdOffset8 = CssStyleName("col-md-offset-8")
    val colMdOffset9 = CssStyleName("col-md-offset-9")
    val colMdPull0 = CssStyleName("col-md-pull-0")
    val colMdPull1 = CssStyleName("col-md-pull-1")
    val colMdPull10 = CssStyleName("col-md-pull-10")
    val colMdPull11 = CssStyleName("col-md-pull-11")
    val colMdPull2 = CssStyleName("col-md-pull-2")
    val colMdPull3 = CssStyleName("col-md-pull-3")
    val colMdPull4 = CssStyleName("col-md-pull-4")
    val colMdPull5 = CssStyleName("col-md-pull-5")
    val colMdPull6 = CssStyleName("col-md-pull-6")
    val colMdPull7 = CssStyleName("col-md-pull-7")
    val colMdPull8 = CssStyleName("col-md-pull-8")
    val colMdPull9 = CssStyleName("col-md-pull-9")
    val colMdPush0 = CssStyleName("col-md-push-0")
    val colMdPush1 = CssStyleName("col-md-push-1")
    val colMdPush10 = CssStyleName("col-md-push-10")
    val colMdPush11 = CssStyleName("col-md-push-11")
    val colMdPush2 = CssStyleName("col-md-push-2")
    val colMdPush3 = CssStyleName("col-md-push-3")
    val colMdPush4 = CssStyleName("col-md-push-4")
    val colMdPush5 = CssStyleName("col-md-push-5")
    val colMdPush6 = CssStyleName("col-md-push-6")
    val colMdPush7 = CssStyleName("col-md-push-7")
    val colMdPush8 = CssStyleName("col-md-push-8")
    val colMdPush9 = CssStyleName("col-md-push-9")
    val colSm1 = CssStyleName("col-sm-1")
    val colSm10 = CssStyleName("col-sm-10")
    val colSm11 = CssStyleName("col-sm-11")
    val colSm12 = CssStyleName("col-sm-12")
    val colSm2 = CssStyleName("col-sm-2")
    val colSm3 = CssStyleName("col-sm-3")
    val colSm4 = CssStyleName("col-sm-4")
    val colSm5 = CssStyleName("col-sm-5")
    val colSm6 = CssStyleName("col-sm-6")
    val colSm7 = CssStyleName("col-sm-7")
    val colSm8 = CssStyleName("col-sm-8")
    val colSm9 = CssStyleName("col-sm-9")
    val colSmOffset1 = CssStyleName("col-sm-offset-1")
    val colSmOffset10 = CssStyleName("col-sm-offset-10")
    val colSmOffset11 = CssStyleName("col-sm-offset-11")
    val colSmOffset2 = CssStyleName("col-sm-offset-2")
    val colSmOffset3 = CssStyleName("col-sm-offset-3")
    val colSmOffset4 = CssStyleName("col-sm-offset-4")
    val colSmOffset5 = CssStyleName("col-sm-offset-5")
    val colSmOffset6 = CssStyleName("col-sm-offset-6")
    val colSmOffset7 = CssStyleName("col-sm-offset-7")
    val colSmOffset8 = CssStyleName("col-sm-offset-8")
    val colSmOffset9 = CssStyleName("col-sm-offset-9")
    val colSmPull1 = CssStyleName("col-sm-pull-1")
    val colSmPull10 = CssStyleName("col-sm-pull-10")
    val colSmPull11 = CssStyleName("col-sm-pull-11")
    val colSmPull2 = CssStyleName("col-sm-pull-2")
    val colSmPull3 = CssStyleName("col-sm-pull-3")
    val colSmPull4 = CssStyleName("col-sm-pull-4")
    val colSmPull5 = CssStyleName("col-sm-pull-5")
    val colSmPull6 = CssStyleName("col-sm-pull-6")
    val colSmPull7 = CssStyleName("col-sm-pull-7")
    val colSmPull8 = CssStyleName("col-sm-pull-8")
    val colSmPull9 = CssStyleName("col-sm-pull-9")
    val colSmPush1 = CssStyleName("col-sm-push-1")
    val colSmPush10 = CssStyleName("col-sm-push-10")
    val colSmPush11 = CssStyleName("col-sm-push-11")
    val colSmPush2 = CssStyleName("col-sm-push-2")
    val colSmPush3 = CssStyleName("col-sm-push-3")
    val colSmPush4 = CssStyleName("col-sm-push-4")
    val colSmPush5 = CssStyleName("col-sm-push-5")
    val colSmPush6 = CssStyleName("col-sm-push-6")
    val colSmPush7 = CssStyleName("col-sm-push-7")
    val colSmPush8 = CssStyleName("col-sm-push-8")
    val colSmPush9 = CssStyleName("col-sm-push-9")
    val colXs1 = CssStyleName("col-xs-1")
    val colXs10 = CssStyleName("col-xs-10")
    val colXs11 = CssStyleName("col-xs-11")
    val colXs12 = CssStyleName("col-xs-12")
    val colXs2 = CssStyleName("col-xs-2")
    val colXs3 = CssStyleName("col-xs-3")
    val colXs4 = CssStyleName("col-xs-4")
    val colXs5 = CssStyleName("col-xs-5")
    val colXs6 = CssStyleName("col-xs-6")
    val colXs7 = CssStyleName("col-xs-7")
    val colXs8 = CssStyleName("col-xs-8")
    val colXs9 = CssStyleName("col-xs-9")
  }

  object Background {
    val bgPrimary = CssStyleName("bg-primary")
    val bgSuccess = CssStyleName("bg-success")
    val bgInfo = CssStyleName("bg-info")
    val bgWarning = CssStyleName("bg-warning")
    val bgDanger = CssStyleName("bg-danger")
  }

  object Button {
    val btn = CssStyleName("btn")
    val btnBlock = CssStyleName("btn-block")
    val btnDanger = CssStyleName("btn-danger")
    val btnDefault = CssStyleName("btn-default")
    val btnGroup = CssStyleName("btn-group")
    val btnGroupJustified = CssStyleName("btn-group-justified")
    val btnGroupVertical = CssStyleName("btn-group-vertical")
    val btnInfo = CssStyleName("btn-info")
    val btnLg = CssStyleName("btn-lg")
    val btnLink = CssStyleName("btn-link")
    val btnPrimary = CssStyleName("btn-primary")
    val btnSuccess = CssStyleName("btn-success")
    val btnToolbar = CssStyleName("btn-toolbar")
    val btnWarning = CssStyleName("btn-warning")
    val btnXs = CssStyleName("btn-xs")
    val btnSm = CssStyleName("btn-sm")
  }

  object Well {
    val well = CssStyleName("well")
    val wellLg = CssStyleName("well-lg")
    val wellSm = CssStyleName("well-sm")
  }

  object Carousel {
    val carousel = CssStyleName("carousel")
    val carouselCaption = CssStyleName("carousel-caption")
    val carouselControl = CssStyleName("carousel-control")
    val carouselIndicators = CssStyleName("carousel-indicators")
    val carouselInner = CssStyleName("carousel-inner")
    val slide = CssStyleName("slide")
  }

  object Alert {
    val alert = CssStyleName("alert")
    val alertDanger = CssStyleName("alert-danger")
    val alertDismissible = CssStyleName("alert-dismissible")
    val alertInfo = CssStyleName("alert-info")
    val alertLink = CssStyleName("alert-link")
    val alertSuccess = CssStyleName("alert-success")
    val alertWarning = CssStyleName("alert-warning")
  }

  object Dropdown {
    val dropdown = CssStyleName("dropdown")
    val dropdownBackdrop = CssStyleName("dropdown-backdrop")
    val dropdownHeader = CssStyleName("dropdown-header")
    val dropdownMenu = CssStyleName("dropdown-menu")
    val dropdownToggle = CssStyleName("dropdown-toggle")
    val dropup = CssStyleName("dropup")
    val caret = CssStyleName("caret")
  }

  object Visibility {
    val clearfix = CssStyleName("clearfix")
    val hidden = CssStyleName("hidden")
    val hiddenLg = CssStyleName("hidden-lg")
    val hiddenMd = CssStyleName("hidden-md")
    val hiddenPrint = CssStyleName("hidden-print")
    val hiddenSm = CssStyleName("hidden-sm")
    val hiddenXs = CssStyleName("hidden-xs")
    val visibleLg = CssStyleName("visible-lg")
    val visibleMd = CssStyleName("visible-md")
    val visiblePrint = CssStyleName("visible-print")
    val visibleSm = CssStyleName("visible-sm")
    val visibleXs = CssStyleName("visible-xs")
    val invisible = CssStyleName("invisible")
    val srOnly = CssStyleName("sr-only")
    val srOnlyFocusable = CssStyleName("sr-only-focusable")
  }

  object Typography {
    val h1 = CssStyleName("h1")
    val h2 = CssStyleName("h2")
    val h3 = CssStyleName("h3")
    val h4 = CssStyleName("h4")
    val h5 = CssStyleName("h5")
    val h6 = CssStyleName("h6")
    val pageHeader = CssStyleName("page-header")
    val lead = CssStyleName("lead")
    val textCenter = CssStyleName("text-center")
    val textDanger = CssStyleName("text-danger")
    val textHide = CssStyleName("text-hide")
    val textInfo = CssStyleName("text-info")
    val textLeft = CssStyleName("text-left")
    val textMuted = CssStyleName("text-muted")
    val textPrimary = CssStyleName("text-primary")
    val textRight = CssStyleName("text-right")
    val textSuccess = CssStyleName("text-success")
    val textWarning = CssStyleName("text-warning")
    val textNoWrap = CssStyleName("text-nowrap")
    val textLowercase = CssStyleName("text-lowercase")
    val textUppercase = CssStyleName("text-uppercase")
    val textCapitalize = CssStyleName("text-capitalize")
    val initialism = CssStyleName("initialism")
  }

  object List {
    val listGroup = CssStyleName("list-group")
    val listGroupItem = CssStyleName("list-group-item")
    val listGroupItemHeading = CssStyleName("list-group-item-heading")
    val listGroupItemText = CssStyleName("list-group-item-text")
    val listInline = CssStyleName("list-inline")
    val listUnstyled = CssStyleName("list-unstyled")
    val listItemSuccess = CssStyleName("list-group-item-success")
    val listItemInfo = CssStyleName("list-group-item-info")
    val listItemWarning = CssStyleName("list-group-item-warning")
    val listItemDanger = CssStyleName("list-group-item-danger")
    val dlHorizontal = CssStyleName("dl-horizontal")
  }

  object Table {
    val table = CssStyleName("table")
    val tableBordered = CssStyleName("table-bordered")
    val tableResponsive = CssStyleName("table-responsive")
    val tableStriped = CssStyleName("table-striped")
    val tableHover = CssStyleName("table-hover")
    val tableCondensed = CssStyleName("table-condensed")
    val success = CssStyleName("success")
    val info = CssStyleName("info")
    val warning = CssStyleName("warning")
    val danger = CssStyleName("danger")
  }

  object Form {
    val formControl = CssStyleName("form-control")
    val formControlStatic = CssStyleName("form-control-static")
    val formGroup = CssStyleName("form-group")
    val formGroupLg = CssStyleName("form-group-lg")
    val formGroupSm = CssStyleName("form-group-sm")
    val formInline = CssStyleName("form-inline")
    val formHorizontal = CssStyleName("form-horizontal")
    val inputGroup = CssStyleName("input-group")
    val inputGroupAddon = CssStyleName("input-group-addon")
    val inputGroupBtn = CssStyleName("input-group-btn")
    val inputGroupLg = CssStyleName("input-group-lg")
    val inputGroupSm = CssStyleName("input-group-sm")
    val inputLg = CssStyleName("input-lg")
    val inputSm = CssStyleName("input-sm")
    val checkbox = CssStyleName("checkbox")
    val checkboxInline = CssStyleName("checkbox-inline")
    val hasWarning = CssStyleName("has-warning")
    val hasError = CssStyleName("has-error")
    val hasSuccess = CssStyleName("has-success")
    val hasFeedback = CssStyleName("has-feedback")
    val helpBlock = CssStyleName("help-block")
    val radio = CssStyleName("radio")
    val radioInline = CssStyleName("radio-inline")
    val controlLabel = CssStyleName("control-label")
  }

  object Image {
    val imgCircle = CssStyleName("img-circle")
    val imgResponsive = CssStyleName("img-responsive")
    val imgRounded = CssStyleName("img-rounded")
    val imgThumbnail = CssStyleName("img-thumbnail")
    val caption = CssStyleName("caption")
    val thumbnail = CssStyleName("thumbnail")

    @deprecated("Use `UdashIcons.FontAwesome.fa` instead.", "0.6.0")
    val _fa = CssStyleName("fa")
    @deprecated("Use `UdashIcons.Glyphicon.glyphicon` instead.", "0.6.0")
    val _glyphicon = CssStyleName("glyphicon")

    @deprecated("Use `UdashIcons.FontAwesome` instead.", "0.6.0")
    def fa(name: String) = Seq(_fa, CssStyleName(s"fa-$name"))
    @deprecated("Use `UdashIcons.FontAwesome` instead.", "0.6.0")
    def glyphicon(name: String) = Seq(_glyphicon, CssStyleName(s"glyphicon-$name"))
  }

  object Navigation {
    val nav = CssStyleName("nav")
    val navbar = CssStyleName("navbar")
    val navbarBrand = CssStyleName("navbar-brand")
    val navbarBtn = CssStyleName("navbar-btn")
    val navbarCollapse = CssStyleName("navbar-collapse")
    val navbarDefault = CssStyleName("navbar-default")
    val navbarFixedBottom = CssStyleName("navbar-fixed-bottom")
    val navbarFixedTop = CssStyleName("navbar-fixed-top")
    val navbarForm = CssStyleName("navbar-form")
    val navbarHeader = CssStyleName("navbar-header")
    val navbarInverse = CssStyleName("navbar-inverse")
    val navbarLeft = CssStyleName("navbar-left")
    val navbarLink = CssStyleName("navbar-link")
    val navbarNav = CssStyleName("navbar-nav")
    val navbarRight = CssStyleName("navbar-right")
    val navbarStaticTop = CssStyleName("navbar-static-top")
    val navbarText = CssStyleName("navbar-text")
    val navbarToggle = CssStyleName("navbar-toggle")
    val navDivider = CssStyleName("nav-divider")
    val navJustified = CssStyleName("nav-justified")
    val navStacked = CssStyleName("nav-stacked")
    val navPills = CssStyleName("nav-pills")
    val navTabs = CssStyleName("nav-tabs")
    val navTabsJustified = CssStyleName("nav-tabs-justified")
    val breadcrumb = CssStyleName("breadcrumb")
  }

  object Label {
    val badge = CssStyleName("badge")
    val label = CssStyleName("label")
    val labelDanger = CssStyleName("label-danger")
    val labelDefault = CssStyleName("label-default")
    val labelInfo = CssStyleName("label-info")
    val labelPrimary = CssStyleName("label-primary")
    val labelSuccess = CssStyleName("label-success")
    val labelWarning = CssStyleName("label-warning")
  }

  object Media {
    val media = CssStyleName("media")
    val mediaBody = CssStyleName("media-body")
    val mediaHeading = CssStyleName("media-heading")
    val mediaList = CssStyleName("media-list")
    val mediaObject = CssStyleName("media-object")
    val mediaLeft = CssStyleName("media-left")
    val mediaMiddle = CssStyleName("media-middle")
    val mediaRight = CssStyleName("media-right")
  }

  object Modal {
    val modal = CssStyleName("modal")
    val modalBackdrop = CssStyleName("modal-backdrop")
    val modalBody = CssStyleName("modal-body")
    val modalContent = CssStyleName("modal-content")
    val modalDialog = CssStyleName("modal-dialog")
    val modalFooter = CssStyleName("modal-footer")
    val modalHeader = CssStyleName("modal-header")
    val modalLarge = CssStyleName("modal-lg")
    val modalOpen = CssStyleName("modal-open")
    val modalSmall = CssStyleName("modal-sm")
    val modalTitle = CssStyleName("modal-title")
  }

  object Pagination {
    val pagination = CssStyleName("pagination")
    val paginationLg = CssStyleName("pagination-lg")
    val paginationSm = CssStyleName("pagination-sm")
    val pager = CssStyleName("pager")
  }

  object Panel {
    val panel = CssStyleName("panel")
    val panelBody = CssStyleName("panel-body")
    val panelCollapse = CssStyleName("panel-collapse")
    val panelDanger = CssStyleName("panel-danger")
    val panelDefault = CssStyleName("panel-default")
    val panelFooter = CssStyleName("panel-footer")
    val panelGroup = CssStyleName("panel-group")
    val panelHeading = CssStyleName("panel-heading")
    val panelInfo = CssStyleName("panel-info")
    val panelPrimary = CssStyleName("panel-primary")
    val panelSuccess = CssStyleName("panel-success")
    val panelTitle = CssStyleName("panel-title")
    val panelWarning = CssStyleName("panel-warning")
  }

  object Popover {
    val popover = CssStyleName("popover")
    val popoverContent = CssStyleName("popover-content")
    val popoverTitle = CssStyleName("popover-title")
  }

  object ProgressBar {
    val progress = CssStyleName("progress")
    val progressBar = CssStyleName("progress-bar")
    val progressBarDanger = CssStyleName("progress-bar-danger")
    val progressBarInfo = CssStyleName("progress-bar-info")
    val progressBarSuccess = CssStyleName("progress-bar-success")
    val progressBarWarning = CssStyleName("progress-bar-warning")
    val progressBarStriped = CssStyleName("progress-bar-striped")
  }

  object Tooltip {
    val tooltip = CssStyleName("tooltip")
    val tooltipArrow = CssStyleName("tooltip-arrow")
    val tooltipInner = CssStyleName("tooltip-inner")
  }

  object EmbedResponsive {
    val embed = CssStyleName("embed-responsive")
    val item = CssStyleName("embed-responsive-item")
    val embed16by9 = CssStyleName("embed-responsive-16by9")
    val embed4by3 = CssStyleName("embed-responsive-4by3")
  }
}