name: Create and publish a Docker image

on:
  push:
    tags: [ "v[0-9]+*" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # only run on tag push
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v'))
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: udashframework
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Get version
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
      - name: Build and push Docker image
        run: >
          sbt
          'set ThisBuild/version := "${{ steps.get_tag_name.outputs.VERSION }}"'
          'project guide-packager'
          'set dockerRepository := Some("${{ env.REGISTRY }}")'
          'set dockerUsername := Some("udashframework")'
          docker:publish
